import json
from datetime import datetime, timedelta
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "data"

# 365 Günlük Manuel ve Temiz Türkçe Kelime Veritabanı
YEARLY_WORDS = [
    # Ocak (1 - 31)
    ["kitap", "kalem", "bilgisayar", "telefon"],
    ["deniz", "güneş", "orman", "şehir"],
    ["müzik", "sahil", "sistem", "bilgi"],
    ["araba", "evren", "bahçe", "yağmur"],
    ["toprak", "rüzgar", "yıldız", "bulut"],
    ["yaprak", "çiçek", "meyve", "ağaç"],
    ["insan", "çocuk", "anne", "baba"],
    ["okul", "sınıf", "öğrenci", "öğretmen"],
    ["dünya", "uzay", "gezegeni", "uydu"],
    ["zaman", "saat", "dakika", "saniye"],
    ["yazar", "roman", "hikaye", "masal"],
    ["resim", "sanat", "tiyatro", "sinema"],
    ["yemek", "ekmek", "sofra", "mutfak"],
    ["kahve", "çay", "fincan", "bardak"],
    ["kapı", "pencere", "duvar", "tavan"],
    ["sokak", "cadde", "meydan", "köprü"],
    ["şehir", "kasaba", "köye", "ülke"],
    ["deniz", "dalga", "liman", "gemi"],
    ["nehir", "ırmak", "vadi", "şelale"],
    ["dağcı", "zirve", "mağara", "patika"],
    ["hava", "ateş", "toprak", "suya"],
    ["ışık", "gölge", "renk", "desen"],
    ["ayna", "camı", "kristal", "elmas"],
    ["altın", "gümüş", "bakır", "demir"],
    ["para", "banka", "borsa", "kredi"],
    ["işletme", "şirket", "büro", "ofis"],
    ["haber", "gazete", "dergi", "radyo"],
    ["telefon", "ekran", "kablo", "batarya"],
    ["yazılım", "kodlama", "mantık", "veri"],
    ["motor", "araba", "tren", "uçak"],
    ["yolcu", "bilet", "istasyon", "peron"],

    # Şubat (32 - 59)
    ["balık", "olta", "ağlar", "sandal"],
    ["kuşlar", "kanat", "yuva", "kafes"],
    ["köpek", "kedi", "sokak", "tasma"],
    ["aslan", "kaplan", "orman", "sahra"],
    ["tarla", "tohum", "hasat", "traktör"],
    ["ekmek", "fırın", "buğday", "hamur"],
    ["peynir", "sütçü", "yoğurt", "tereyağı"],
    ["meyve", "elma", "armut", "karpuz"],
    ["sebze", "domates", "biber", "patates"],
    ["giysi", "kazak", "pantolon", "ceket"],
    ["ayakkabı", "çorap", "kemer", "şapka"],
    ["çanta", "valiz", "bavul", "cüzdan"],
    ["sabun", "havlu", "banyo", "tarama"],
    ["yatak", "yastık", "yorgan", "çarşaf"],
    ["koltuk", "sehpa", "halı", "perde"],
    ["mermer", "fayans", "beton", "tuğla"],
    ["çekiç", "çivi", "pense", "matkap"],
    ["lamba", "ampul", "fener", "mumlar"],
    ["kutu", "sandık", "sepet", "paket"],
    ["makas", "bıçak", "çatal", "kaşık"],
    ["tabak", "tava", "tencere", "cezve"],
    ["şeker", "tuzlu", "baharat", "sirke"],
    ["tatlı", "pasta", "börek", "çikolata"],
    ["dondurma", "şerbet", "reçel", "balım"],
    ["meyve", "portakal", "limon", "mandalina"],
    ["üzüm", "incir", "ceviz", "fındık"],
    ["zeytin", "yağlı", "turşu", "salata"],
    ["çorba", "pilav", "makarna", "etli"],

    # Mart (60 - 90)
    ["bahar", "güneş", "yeşil", "doğa"],
    ["fidan", "yaprak", "çiçek", "tohum"],
    ["yağmur", "bulut", "şimşek", "rüzgar"],
    ["nehir", "dere", "gölü", "akarsu"],
    ["orman", "ağaç", "koru", "çalı"],
    ["kuşlar", "leylek", "kırlangıç", "serçe"],
    ["arılar", "petek", "balım", "çiçek"],
    ["kelebek", "tırtıl", "renkli", "kanat"],
    ["karınca", "yuva", "toprak", "emek"],
    ["güneş", "ışık", "sıcak", "gündüz"],
    ["gece", "yıldız", "dolunay", "karanlık"],
    ["uyku", "rüya", "masal", "yatak"],
    ["sabah", "kahvaltı", "şafak", "güneş"],
    ["akşam", "yemek", "huzur", "sessizlik"],
    ["hafta", "pazar", "tatil", "dinlenme"],
    ["mevsim", "yazlar", "sonbahar", "kışlar"],
    ["takvim", "tarih", "yılbaşı", "zaman"],
    ["doğum", "yaşlar", "parti", "hediye"],
    ["düğün", "halay", "müzik", "eğlence"],
    ["oyun", "oyuncak", "parkı", "salıncak"],
    ["toplar", "kale", "saha", "takım"],
    ["koşu", "yürüyüş", "spor", "sağlık"],
    ["yüzme", "havuz", "plaj", "güneş"],
    ["bisiklet", "pedal", "kaskı", "yolcu"],
    ["satranç", "tahta", "kale", "piyon"],
    ["kartal", "şahin", "doğan", "akbaba"],
    ["balık", "yunus", "balina", "köpekbalığı"],
    ["kaplumbağa", "tavşan", "masal", "yarış"],
    ["tilki", "kurtlar", "ayılar", "geyik"],
    ["atlar", "eğer", "çiftlik", "jokey"],
    ["deve", "çölün", "vaha", "kumlar"],

    # Nisan (91 - 120)
    ["bayrak", "millet", "vatan", "özgürlük"],
    ["okul", "tören", "şiirler", "coşku"],
    ["çocuk", "gülüş", "sevinç", "oyun"],
    ["kitap", "kütüphane", "rafı", "okuma"],
    ["defter", "sayfa", "notlar", "kalem"],
    ["sıra", "tahta", "tebeşir", "silgi"],
    ["sınav", "soru", "cevap", "başarı"],
    ["diploma", "mezun", "kepçe", "tören"],
    ["bilim", "deney", "laboratuvar", "teori"],
    ["uzay", "roket", "mekik", "astronot"],
    ["fizik", "kimya", "biyoloji", "matematik"],
    ["hesap", "sayı", "toplam", "oran"],
    ["geometri", "açılar", "üçgen", "kare"],
    ["harita", "pusula", "yönler", "kutup"],
    ["küre", "atlas", "kıta", "okyanus"],
    ["müze", "tarih", "heykeller", "kalıntı"],
    ["kale", "surlar", "kule", "hendek"],
    ["saray", "sultan", "krallık", "tacım"],
    ["kılıç", "kalkan", "zırhı", "okçu"],
    ["savaş", "barış", "zafer", "ordu"],
    ["heykel", "ressam", "mimar", "eser"],
    ["müzik", "şarkı", "melodi", "ritim"],
    ["gitar", "keman", "piyano", "flüt"],
    ["davul", "zurna", "orgu", "bağlama"],
    ["tiyatro", "sahne", "perde", "oyuncu"],
    ["sinema", "filmi", "kamera", "perde"],
    ["dans", "bale", "vals", "figür"],
    ["mimar", "proje", "çizim", "bina"],
    ["mühendis", "sistem", "köprü", "yolcu"],
    ["doktor", "hasta", "teşhis", "tedavi"],

    # Mayıs (121 - 151)
    ["hemşire", "iğne", "ilaçlar", "reçete"],
    ["eczane", "haplar", "şurup", "sargı"],
    ["hastane", "odası", "sedye", "ambulans"],
    ["sağlık", "virüs", "bakteri", "bağışıklık"],
    ["sporcu", "stadyum", "tribün", "taraftar"],
    ["hakem", "düdük", "kartlar", "faul"],
    ["madalya", "kupa", "kürsü", "şampiyon"],
    ["güreş", "minder", "boksör", "ring"],
    ["tenis", "raket", "file", "kort"],
    ["basketbol", "pota", "saha", "smaç"],
    ["voleybol", "pasör", "blok", "servis"],
    ["kayak", "karla", "dağcı", "skilift"],
    ["kampçı", "çadır", "tulum", "fener"],
    ["doğa", "yürüyüş", "mola", "matra"],
    ["yangın", "itfaiye", "hortum", "siren"],
    ["polis", "devriye", "telsiz", "asayiş"],
    ["asker", "kışla", "nöbet", "üniforma"],
    ["posta", "mektup", "zarfı", "pulcu"],
    ["kargo", "paket", "teslim", "adres"],
    ["mesaj", "sohbet", "telefon", "bildirim"],
    ["internet", "ağlar", "web3", "sunucu"],
    ["veri", "ekran", "klavye", "fare"],
    ["yazıcı", "tarayıcı", "kağıt", "mürekkepli"],
    ["fotoğraf", "flaş", "lens", "albümi"],
    ["video", "kurgu", "sesi", "ışık"],
    ["radyo", "yayın", "stüdyo", "mikrofon"],
    ["televizyon", "kanal", "dizi", "reklam"],
    ["gazete", "manşet", "yazar", "baskı"],
    ["dergi", "kapak", "makale", "görsel"],
    ["reklam", "afiş", "pano", "marka"],
    ["ticaret", "pazar", "müşteri", "satış"],

    # Haziran (152 - 181)
    ["yazlar", "sıcak", "güneş", "tatil"],
    ["deniz", "kumsal", "şezlong", "şemsiye"],
    ["dondurma", "külah", "meyve", "serinlik"],
    ["karpuz", "kavun", "soğuk", "dilim"],
    ["piknik", "mangal", "ızgara", "çimen"],
    ["parkı", "havuz", "kaydırak", "eğlence"],
    ["yolculuk", "otobüs", "bilet", "mola"],
    ["oteller", "resepsiyon", "anahtar", "oda"],
    ["bavul", "giysi", "gözlük", "krem"],
    ["iskele", "gemi", "vapur", "simit"],
    ["martı", "deniz", "rüzgar", "dalga"],
    ["balıkçı", "ağlar", "tekne", "koylar"],
    ["dalgıç", "tüpü", "palet", "mercan"],
    ["ada", "fener", "sahil", "kayalık"],
    ["denizyıldızı", "kabuk", "kumlar", "yosun"],
    ["kanyon", "şelale", "vadisi", "akarsu"],
    ["mağara", "sarkıt", "dikit", "fener"],
    ["ormancı", "ağaç", "yeşil", "yaban"],
    ["kamp ateşi", "odun", "duman", "kıvılcım"],
    ["gökyüzü", "bulut", "mavi", "uçak"],
    ["paraşüt", "atlayış", "rüzgar", "cesaret"],
    ["balon", "kapadokya", "peri", "uçuş"],
    ["gezgin", "maceracı", "rota", "harita"],
    ["fotoğrafçı", "manzara", "kadraj", "odak"],
    ["düğün", "gelin", "damat", "yüzük"],
    ["çiçekçi", "gülü", "papatya", "demet"],
    ["müzik", "orkestra", "keman", "sahne"],
    ["ziyafet", "garson", "menü", "sipariş"],
    ["restoran", "şefin", "lezzet", "servis"],
    ["lokanta", "çorba", "kebabı", "tatlı"],

    # Temmuz (182 - 212)
    ["güneş", "kumlar", "deniz", "bronz"],
    ["şapka", "gözlük", "havlu", "terlik"],
    ["limonata", "buzlu", "nane", "ferahlık"],
    ["meyve", "şeftali", "kayısı", "kiraz"],
    ["dondurma", "vanilya", "kakao", "fıstık"],
    ["palmiye", "sahil", "esinti", "akşam"],
    ["dalga", "sörf", "board", "dengeli"],
    ["yatı", "marina", "dümen", "kaptan"],
    ["pusula", "yönler", "harita", "keşif"],
    ["hazine", "sandık", "altın", "harita"],
    ["korsan", "bayrak", "gemi", "toplar"],
    ["denizanası", "derinlik", "mavi", "yüzme"],
    ["akvaryum", "balık", "camı", "renkli"],
    ["yazlık", "balkon", "hamak", "huzur"],
    ["müzik", "konser", "festival", "bilet"],
    ["sahne", "ışık", "hoparlör", "coşku"],
    ["dansçı", "ritim", "müzik", "gösteri"],
    ["lunapark", "dönmedolap", "tren", "eğlence"],
    ["pamuk", "şeker", "balon", "çocuk"],
    ["sirki", "palyaço", "gösteri", "alkış"],
    ["sihirbaz", "şapka", "tavşan", "numara"],
    ["oyuncu", "senaryo", "sahne", "yönetmen"],
    ["kamera", "çekim", "setler", "stüdyo"],
    ["kurgu", "montaj", "sesi", "efekt"],
    ["animasyon", "çizim", "karakter", "renk"],
    ["çizgi", "roman", "mizah", "dergi"],
    ["karikatür", "çizim", "esprili", "mürekkep"],
    ["mizaç", "gülüş", "kahkaha", "şaka"],
    ["fıkra", "anlatı", "komedi", "tiyatro"],
    ["maske", "kostüm", "parti", "dans"],
    ["festival", "karnaval", "müzik", "geçit"],

    # Ağustos (213 - 243)
    ["sıcaklık", "gölge", "rüzgar", "klima"],
    ["suya", "sürahi", "bardak", "buzlu"],
    ["karpuz", "peynir", "sofra", "akşam"],
    ["yıldız", "meteor", "gece", "dilek"],
    ["samanyolu", "uzay", "teleskop", "gözlem"],
    ["astronot", "roket", "yerçekimi", "istasyon"],
    ["uzaylı", "gezegen", "krater", "galaksi"],
    ["mimar", "tasarım", "çizim", "maket"],
    ["inşaat", "vinç", "iskele", "beton"],
    ["mühendis", "köprü", "tünel", "otoban"],
    ["yolcu", "asfalt", "viraj", "tabela"],
    ["trafik", "lamba", "araç", "sürücü"],
    ["otobüs", "durak", "yolcu", "bilet"],
    ["metro", "istasyon", "vagon", "raylar"],
    ["taksi", "taksimetre", "şoför", "şehir"],
    ["bisiklet", "tekerlek", "zincir", "fren"],
    ["motosiklet", "kaskı", "egzoz", "hızlar"],
    ["uçak", "kanat", "pilot", "havalimanı"],
    ["helikopter", "pervane", "pist", "uçuş"],
    ["zeplin", "balon", "gazlar", "gökyüzü"],
    ["liman", "vinç", "konteyner", "yükler"],
    ["gemi", "güverte", "baca", "yakıt"],
    ["sandal", "rekreasyon", "gölü", "ördek"],
    ["kuğu", "tüyü", "zarafet", "suya"],
    ["nilüfer", "yaprak", "gölü", "pembe"],
    ["sazlık", "kamış", "kuşlar", "bataklık"],
    ["orman", "milli", "parkı", "koruma"],
    ["izci", "fular", "çadır", "düğüm"],
    ["dağcılık", "tırmanış", "halat", "kanca"],
    ["mağaracılık", "fener", "kaskı", "harita"],
    ["zafer", "bayrak", "tören", "millet"],

    # Eylül (244 - 273)
    ["sonbahar", "rüzgar", "yaprak", "sarı"],
    ["okul", "zilimiz", "önlük", "çanta"],
    ["öğretmen", "ders", "sınıf", "sıra"],
    ["öğrenci", "defter", "kitap", "kalem"],
    ["ödev", "çalışma", "proje", "sunum"],
    ["kütüphane", "sessizlik", "rafı", "araştırma"],
    ["sözlük", "kelime", "anlam", "dilim"],
    ["ansiklopedi", "bilgi", "ciltli", "sayfa"],
    ["kalemkutusu", "silgi", "cetvel", "pergel"],
    ["çanta", "askı", "matara", "beslenme"],
    ["zilimiz", "teneffüs", "bahçe", "oyun"],
    ["kantin", "tostlu", "ayran", "kuyruk"],
    ["spor", "salon", "pota", "voleybol"],
    ["laboratuvar", "önlük", "tüpü", "deney"],
    ["bilgisayar", "yazılım", "internet", "kodlama"],
    ["robot", "sensör", "yazılım", "devre"],
    ["elektronik", "direnç", "akım", "voltaj"],
    ["enerji", "elektrik", "üretim", "şebeke"],
    ["santral", "baraj", "türbin", "suya"],
    ["güneş", "panel", "hücre", "temiz"],
    ["rüzgar", "gülü", "pervane", "tribün"],
    ["doğal", "gazlar", "boru", "kombi"],
    ["kömür", "maden", "ocak", "işçi"],
    ["petrol", "rafineri", "yakıt", "benzin"],
    ["plastik", "geri dönüşüm", "atık", "çevre"],
    ["orijin", "camı", "kağıt", "kutular"],
    ["ağaç", "fidan", "orman", "doğa"],
    ["toprak", "gübre", "sulama", "tarım"],
    ["çiftçi", "tarlalar", "traktör", "ekim"],
    ["buğday", "başak", "değirmen", "unlu"],

    # Ekim (274 - 304)
    ["cumhuriyet", "bayrak", "özgürlük", "tören"],
    ["yağmur", "şemsiye", "yağmurluk", "çizme"],
    ["rüzgar", "fırtına", "yaprak", "soğuk"],
    ["sisli", "bulut", "gri", "hava"],
    ["kestane", "fırın", "soba", "sıcak"],
    ["çaylar", "demlik", "bardak", "şeker"],
    ["kahve", "çekirdek", "değirmen", "fincan"],
    ["çikolata", "kakao", "sütlü", "fındık"],
    ["pasta", "krema", "mumlar", "dilim"],
    ["bisküvi", "kurabiye", "fırın", "unlu"],
    ["fırıncı", "tepsi", "ekmek", "simit"],
    ["pazar", "tezgah", "terazi", "file"],
    ["manav", "meyve", "sebze", "taze"],
    ["kasap", "bıçak", "kıyma", "bonfile"],
    ["balıkçı", "hamsi", "tezgah", "buzlu"],
    ["market", "kasa", "sepet", "fişli"],
    ["alışveriş", "poşet", "kartlar", "indirim"],
    ["mağaza", "vitrin", "manken", "askı"],
    ["terzi", "iğne", "iplik", "kumaş"],
    ["dikiş", "makine", "desen", "prova"],
    ["elbise", "gömlek", "pantolon", "ceket"],
    ["ayakkabı", "bağcık", "taban", "deri"],
    ["çanta", "deri", "fermuar", "toka"],
    ["takı", "yüzük", "kolye", "bilezik"],
    ["saatçi", "akrep", "yelkovan", "zemberek"],
    ["gözlükçü", "çerçeve", "camı", "lens"],
    ["kuaför", "makas", "tarak", "fön"],
    ["berber", "ustura", "krem", "ayna"],
    ["parfüm", "koku", "şişe", "esans"],
    ["kozmetik", "rujlar", "krem", "bakım"],
    ["temizlik", "sabun", "fırça", "sünger"],

    # Kasım (305 - 334)
    ["öğretmen", "sevgi", "saygı", "bilgi"],
    ["yaprak", "toprak", "sarı", "kuru"],
    ["soğuk", "rüzgar", "montu", "atkı"],
    ["elden", "eldiven", "bere", "şal"],
    ["soba", "odun", "kömür", "baca"],
    ["kalorifer", "petek", "sıcak", "kombi"],
    ["pencere", "buğu", "yağmur", "damla"],
    ["şemsiye", "rüzgar", "yağmurluk", "ıslak"],
    ["çamur", "çizme", "sokak", "su birikintisi"],
    ["çorba", "sıcak", "kase", "kaşık"],
    ["ıhlamur", "tarçın", "zencefil", "balım"],
    ["bitki", "çaylar", "demlik", "süzgeç"],
    ["kitap", "battaniye", "huzur", "koltuk"],
    ["müzik", "plak", "pikap", "nostalji"],
    ["radyo", "yayın", "sesi", "dalga"],
    ["sinema", "bilet", "mısır", "salon"],
    ["tiyatro", "sahne", "mimler", "alkış"],
    ["opera", "sanatçı", "sahne", "sesi"],
    ["müze", "galeri", "tablo", "sergi"],
    ["ressam", "fırça", "tuval", "boya"],
    ["heykel", "mermer", "kiKi", "sanat"],
    ["fotoğraf", "kamera", "sergi", "kare"],
    ["yazar", "daktilo", "kağıt", "mürekkep"],
    ["şair", "şiirler", "kıta", "mısra"],
    ["edebiyat", "dergi", "makale", "eleştiri"],
    ["felsefe", "düşünce", "akıl", "soru"],
    ["mantık", "doğru", "yanlış", "sonuç"],
    ["bilim", "deney", "gözlem", "kanıt"],
    ["tarih", "geçmiş", "belge", "arşiv"],
    ["coğrafya", "harita", "iklim", "yerşekli"],

    # Aralık (335 - 365)
    ["kışlar", "karla", "soğuk", "rüzgar"],
    ["kartopu", "oyun", "çocuk", "eğlence"],
    ["kardan adam", "havuç", "kömür", "atkı"],
    ["buzlar", "paten", "pist", "kayma"],
    ["kayak", "dağcı", "karla", "montu"],
    ["kızak", "eğim", "hızlar", "eğlence"],
    ["çam ağacı", "kozalak", "yeşil", "orman"],
    ["süsler", "ışık", "yıldız", "kırmızı"],
    ["hediye", "paket", "kurdele", "sürpriz"],
    ["yılbaşı", "takvim", "aralık", "gece"],
    ["saat", "gece yarısı", "yeni yıl", "umut"],
    ["dilek", "mektup", "zarfı", "hayal"],
    ["kutlama", "parti", "müzik", "coşku"],
    ["pasta", "mumlar", "dilim", "ikram"],
    ["kestane", "fırın", "közde", "Sıcak"],
    ["salep", "tarçın", "fincan", "duman"],
    ["boza", "leblebi", "tarçın", "güban"],
    ["ceviz", "fındık", "badem", "kuru üzüm"],
    ["incir", "günkurusu", "reçel", "tatlı"],
    ["balkabak", "fırın", "tahin", "ceviz"],
    ["narım", "tane", "kırmızı", "bereket"],
    ["portakal", "tarçın", "koku", "dilim"],
    ["mandina", "kabuk", "vitamin", "taze"],
    ["evim", "huzur", "soba", "aile"],
    ["sofra", "akşam", "yemeği", "sohbet"],
    ["dostluk", "güven", "sevgi", "paylaşım"],
    ["teşekkür", "tebessüm", "iyilik", "kalp"],
    ["yolculuk", "anıları", "fotoğraf", "günlük"],
    ["zaman", "hatıra", "geçmiş", "Gelecek"],
    ["yeni", "başlangıç", "hedef", "başarı"],
    ["mutluluk", "sağlık", "huzur", "şans"]
]

WORD_REPLACEMENTS = {
    "gezegeni": "gezegen", "köye": "köy", "suya": "su", "camı": "cam",
    "ağlar": "ağ", "kuşlar": "kuş", "mumlar": "mum", "tuzlu": "tuz",
    "balım": "bal", "yağlı": "yağ", "etli": "et", "gölü": "göl",
    "arılar": "arı", "yazlar": "yaz", "yaşlar": "yaş", "parkı": "park",
    "kaskı": "kask", "kurtlar": "kurt", "ayılar": "ayı", "atlar": "at",
    "eğer": "eyer", "çölün": "çöl", "kumlar": "kum", "şiirler": "şiir",
    "rafı": "raf", "notlar": "not", "açılar": "açı", "yönler": "yön",
    "heykeller": "heykel", "surlar": "sur", "tacım": "taç", "zırhı": "zırh",
    "filmi": "film", "orgu": "org", "ilaçlar": "ilaç", "haplar": "hap",
    "odası": "oda", "kartlar": "kart", "karla": "kar", "toplar": "top",
    "mürekkepli": "mürekkep", "albümi": "albüm", "sesi": "ses",
    "oteller": "otel", "koylar": "koy", "tüpü": "tüp", "vadisi": "vadi",
    "gülü": "gül", "şefin": "şef", "kebabı": "kebap", "board": "tahta",
    "yatı": "yat", "setler": "set", "sirki": "sirk", "gazlar": "gaz",
    "yükler": "yük", "tüyü": "tüy", "zilimiz": "zil", "ciltli": "cilt",
    "kalemkutusu": "kalem", "kampçı": "izci", "pulcu": "pul",
    "dönmedolap": "salıncak", "tostlu": "tost", "tarlalar": "tarla",
    "unlu": "un", "çaylar": "çay", "sütlü": "süt", "fişli": "fiş",
    "rujlar": "ruj", "montu": "mont", "elden": "el", "mimler": "rol",
    "kiki": "kil", "yerşekli": "arazi", "kışlar": "kış", "buzlar": "buz",
    "süsler": "süs", "közde": "köz", "güban": "şeker", "günkurusu": "kayısı",
    "balkabak": "balkabağı", "narım": "nar", "mandina": "mandalina",
    "evim": "ev", "yemeği": "yemek", "anıları": "anı", "kamp ateşi": "kamp",
    "geri dönüşüm": "dönüşüm", "su birikintisi": "birikinti", "kardan adam": "kış",
    "çam ağacı": "çam", "gece yarısı": "gece", "yeni yıl": "yıl",
    "kuru üzüm": "üzüm", "matra": "matara", "skilift": "telesiyej",
    "web3": "site", "orijin": "köken"
}

EXTRA_DAYS = [
    ["merak", "keşif", "ipucu", "bulmaca"],
    ["pusula", "yön", "harita", "rota"],
    ["biber", "domates", "soğan", "sarımsak"],
    ["şafak", "günbatımı", "alacakaranlık", "ufuk"],
    ["tohum", "filiz", "kök", "dal"],
    ["defter", "mürekkep", "kalem", "silgi"],
    ["başlangıç", "döngü", "mevsim", "takvim"]
]

START_DATE = datetime(2026, 10, 6)


def generate_full_year_database():
    """6 Ekim 2026'dan başlayan 365 gün ve 7 yedek günü hazırlar."""
    if len(YEARLY_WORDS) != 365:
        raise ValueError(f"Ana kelime havuzu 365 gün olmalı; bulunan: {len(YEARLY_WORDS)}")

    start_day_offset = (START_DATE - datetime(START_DATE.year, 1, 1)).days
    scheduled_words = (
        YEARLY_WORDS[start_day_offset:]
        + YEARLY_WORDS[:start_day_offset]
        + EXTRA_DAYS
    )
    dataset = {}

    for i, words in enumerate(scheduled_words):
        clean_words = [WORD_REPLACEMENTS.get(word.lower(), word.lower()) for word in words]
        if len(clean_words) != 4 or any(not word.isalpha() for word in clean_words):
            raise ValueError(f"Geçersiz günlük kelime grubu: {words}")
        if len(set(clean_words)) != 4:
            raise ValueError(f"Aynı gün tekrarlanan kelime var: {clean_words}")

        current_date = (START_DATE + timedelta(days=i)).strftime("%Y-%m-%d")
        dataset[current_date] = {
            "mode_1_word_kelime_1": clean_words[0],
            "mode_3_word_kelime_1": clean_words[1],
            "mode_3_word_kelime_2": clean_words[2],
            "mode_3_word_kelime_3": clean_words[3]
        }

    with open(DATA_DIR / "year_game_data.json", "w", encoding="utf-8") as f:
        json.dump(dataset, f, ensure_ascii=False, indent=4)
    last_date = next(reversed(dataset))
    print(f"✅ {len(dataset)} günlük kelime veritabanı {START_DATE:%Y-%m-%d} - {last_date} aralığına yazıldı.")

if __name__ == "__main__":
    generate_full_year_database()